## 4.1 NumPy的ndarray：一种多维数组对象

> 引入NumPy，然后生成一个包含随机数据的小数组：

In [1]:
import numpy as np
#generate radom data
data = np.random.randn(2,3) #generate 2 dimensions and 3 objs array
data

array([[-1.90211052, -0.15273567,  0.10553237],
       [ 1.53647334,  0.78150935,  0.77829651]])

In [2]:
data * 10

array([[-19.02110523,  -1.52735665,   1.05532367],
       [ 15.3647334 ,   7.81509355,   7.78296508]])

In [3]:
data + data

array([[-3.80422105, -0.30547133,  0.21106473],
       [ 3.07294668,  1.56301871,  1.55659302]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

> 创建数组最简单的办法就是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [6]:
data1 = [2,3.2,9,11,32]
arr1 = np.array(data1)
arr1#发现全统一为小数形式了

array([ 2. ,  3.2,  9. , 11. , 32. ])

> 嵌套序列（比如由一组等⻓列表组成的列表）将会被转换为一个多维数组：

In [7]:
data2 = [[1,2,2,3,3],[4,4,3,1,2]]
arr2 = np.array(data2)
print (arr2)
print (arr2.ndim) #number of dimension
print (arr2.shape)
arr2.dtype

[[1 2 2 3 3]
 [4 4 3 1 2]]
2
(2, 5)


dtype('int64')

> 除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定⻓度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

> arange是Python内置函数range的数组版

In [11]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### dtype

In [14]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

> 使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

### Numpy数组的运算

In [22]:
arr = np.array([[1.,2,3,4],[3,4,1,2]])
arr

array([[1., 2., 3., 4.],
       [3., 4., 1., 2.]])

In [24]:
arr*arr

array([[ 1.,  4.,  9., 16.],
       [ 9., 16.,  1.,  4.]])

In [25]:
arr - 1

array([[0., 1., 2., 3.],
       [2., 3., 0., 1.]])

In [28]:
arr2 = np.array([[3,1,2,1],[5,2,1,1,]])
arr > arr2

array([[False,  True,  True,  True],
       [False,  True, False,  True]])

### 基本的索引和切片

In [33]:
arr = np.arange(10)
arr

arr[5]
arr[5:8] = 1
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

> 注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。

### 切片索引

In [37]:
arr2d = np.array([[1,2,3],[4,3,2],[5,6,3]])
arr2d[:2,1:]

array([[2, 3],
       [3, 2]])

In [39]:
arr2d[:2,2]

array([3, 2])

> 注意，“只有冒号”表示选取整个轴

### 布尔型索引

In [42]:
names = np.array(['aaa','ccc','rrr'])
names

array(['aaa', 'ccc', 'rrr'], dtype='<U3')

In [49]:
data = np.random.randn(3,5)
data

array([[-0.02539965,  1.57162809, -0.10445727,  1.59685052,  0.22421246],
       [ 1.5920753 , -0.41903222,  1.38005935,  1.34879607,  0.13552601],
       [-0.31400011, -2.04854324, -0.16905569, -0.80422967, -0.69749094]])

In [45]:
names == 'rrr'

array([False, False,  True])

In [50]:
data[names == 'ccc']

array([[ 1.5920753 , -0.41903222,  1.38005935,  1.34879607,  0.13552601]])

> 布尔型数组的⻓度必须跟被索引的轴⻓度一致

### 花式索引

In [63]:
arr = np.array((8,4))
for i in range(7):
    arr[i] = i

IndexError: index 2 is out of bounds for axis 0 with size 2