## 4.1 NumPy的ndarray：一种多维数组对象

> 引入NumPy，然后生成一个包含随机数据的小数组：

In [1]:
import numpy as np
#generate radom data
data = np.random.randn(2,3) #generate 2 dimensions and 3 objs array
data

array([[-1.90211052, -0.15273567,  0.10553237],
       [ 1.53647334,  0.78150935,  0.77829651]])

In [2]:
data * 10

array([[-19.02110523,  -1.52735665,   1.05532367],
       [ 15.3647334 ,   7.81509355,   7.78296508]])

In [3]:
data + data

array([[-3.80422105, -0.30547133,  0.21106473],
       [ 3.07294668,  1.56301871,  1.55659302]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

> 创建数组最简单的办法就是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [6]:
data1 = [2,3.2,9,11,32]
arr1 = np.array(data1)
arr1#发现全统一为小数形式了

array([ 2. ,  3.2,  9. , 11. , 32. ])

> 嵌套序列（比如由一组等⻓列表组成的列表）将会被转换为一个多维数组：

In [7]:
data2 = [[1,2,2,3,3],[4,4,3,1,2]]
arr2 = np.array(data2)
print (arr2)
print (arr2.ndim) #number of dimension
print (arr2.shape)
arr2.dtype

[[1 2 2 3 3]
 [4 4 3 1 2]]
2
(2, 5)


dtype('int64')

> 除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定⻓度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

> arange是Python内置函数range的数组版

In [11]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### dtype

In [14]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

> 使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

### Numpy数组的运算

In [22]:
arr = np.array([[1.,2,3,4],[3,4,1,2]])
arr

array([[1., 2., 3., 4.],
       [3., 4., 1., 2.]])

In [24]:
arr*arr

array([[ 1.,  4.,  9., 16.],
       [ 9., 16.,  1.,  4.]])

In [25]:
arr - 1

array([[0., 1., 2., 3.],
       [2., 3., 0., 1.]])

In [28]:
arr2 = np.array([[3,1,2,1],[5,2,1,1,]])
arr > arr2

array([[False,  True,  True,  True],
       [False,  True, False,  True]])

### 基本的索引和切片

In [33]:
arr = np.arange(10)
arr

arr[5]
arr[5:8] = 1
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

> 注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。

### 切片索引

In [37]:
arr2d = np.array([[1,2,3],[4,3,2],[5,6,3]])
arr2d[:2,1:]

array([[2, 3],
       [3, 2]])

In [39]:
arr2d[:2,2]

array([3, 2])

> 注意，“只有冒号”表示选取整个轴

### 布尔型索引

In [42]:
names = np.array(['aaa','ccc','rrr'])
names

array(['aaa', 'ccc', 'rrr'], dtype='<U3')

In [49]:
data = np.random.randn(3,5)
data

array([[-0.02539965,  1.57162809, -0.10445727,  1.59685052,  0.22421246],
       [ 1.5920753 , -0.41903222,  1.38005935,  1.34879607,  0.13552601],
       [-0.31400011, -2.04854324, -0.16905569, -0.80422967, -0.69749094]])

In [45]:
names == 'rrr'

array([False, False,  True])

In [50]:
data[names == 'ccc']

array([[ 1.5920753 , -0.41903222,  1.38005935,  1.34879607,  0.13552601]])

> 布尔型数组的⻓度必须跟被索引的轴⻓度一致

### 花式索引

In [80]:
# 花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引
arr = np.empty((8,4),dtype='int')
for i in range(7):
    arr[i] = i
arr

array([[         0,          0,          0,          0],
       [         1,          1,          1,          1],
       [         2,          2,          2,          2],
       [         3,          3,          3,          3],
       [         4,          4,          4,          4],
       [         5,          5,          5,          5],
       [         6,          6,          6,          6],
       [4294967296,          0,          0,          0]])

In [82]:
arr[[4,3,0,6]]

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [0, 0, 0, 0],
       [6, 6, 6, 6]])

### 数组转置和轴对换

In [86]:
#转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。
#数组不仅有transpose方法，还有一个特殊的T属性：
arr = np.arange(20).reshape((4,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [100]:
#利用np.dot计算矩阵内积
arr = np.random.randn(6, 3)
arr

array([[-0.2881213 ,  1.06285492, -0.43795043],
       [ 0.63310313, -0.0674097 ,  0.38901479],
       [ 0.46838136,  1.44128491, -0.14917128],
       [-0.7334841 ,  0.23989482, -0.08622727],
       [-1.53004524,  0.53598792, -1.93770353],
       [ 0.48391044,  0.61129359,  0.95986329]])

In [101]:
np.dot(arr,arr.T)

array([[ 1.40447504, -0.42442643,  1.46225573,  0.50406905,  1.85913412,
         0.08991895],
       [-0.42442643,  0.55669615,  0.14134728, -0.514086  , -1.75860254,
         0.63855911],
       [ 1.46225573,  0.14134728,  2.31893535,  0.01506913,  0.34491636,
         0.96451881],
       [ 0.50406905, -0.514086  ,  0.01506913,  0.60298359,  1.41792746,
        -0.29106084],
       [ 1.85913412, -1.75860254,  0.34491636,  1.41792746,  6.38301647,
        -2.27268938],
       [ 0.08991895,  0.63855911,  0.96451881, -0.29106084, -2.27268938,
         1.5291867 ]])

In [102]:
#对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置
#?????????
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [103]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## 通用函数：快速的元素级数组函数

通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。

In [105]:
#许多ufunc都是简单的元素级变体，如sqrt和exp
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])